image: python:3.7

pipelines:
  default:
    - step:
        name: Tests
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python3 -m unittest discover
  tags:
    '*':
      - step:
          name: Release New Verison
          script:
            - chmod +x ./bin/deploy.sh
            - ./bin/deploy.sh